#
# Copyright © 2025 Taras Paruta (partarstu@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

steps:
  - name: 'maven:3.9.11-eclipse-temurin-25'
    dir: '/workspace'
    args: [ 'mvn', 'clean', 'install', '-DskipTests', '-P', 'linux', '-pl', 'ui_test_execution_agent', '-am' ]

  - name: 'gcr.io/cloud-builders/docker'
    dir: '/workspace'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_UI_AGENT_SERVICE_NAME:$_IMAGE_TAG', '-f', 'deployment/cloud/Dockerfile.cloud', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/$_UI_AGENT_SERVICE_NAME:$_IMAGE_TAG' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [ '-c', 'chmod +x deployment/cloud/deploy_vm.sh' ]
    dir: '/workspace'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [ '-c', 'deployment/cloud/deploy_vm.sh' ]
    dir: '/workspace'
    env:
      - 'SERVICE_NAME=$_UI_AGENT_SERVICE_NAME'
      - 'IMAGE_TAG=$_IMAGE_TAG'

substitutions:
  _UI_AGENT_SERVICE_NAME: 'ui-test-execution-agent'
  _IMAGE_TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY