#
# Copyright © 2025 Taras Paruta (partarstu@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Master Cloud Build configuration for deploying agents.
# Use _DEPLOY_TARGET substitution to control which agent(s) to deploy:
#   - 'all' (default): Deploy both UI and API agents
#   - 'ui': Deploy only the UI agent
#   - 'api': Deploy only the API agent

steps:
  # ============================================
  # Stage 1: Build all Maven modules
  # ============================================
  - name: 'maven:3.9.11-eclipse-temurin-25'
    id: 'maven-build'
    dir: '/workspace'
    args: [ 'mvn', 'clean', 'install', '-DskipTests', '-P', 'linux' ]

  # ============================================
  # Stage 2: UI Test Execution Agent (VM-based)
  # Delegates to the module's own cloudbuild.yaml
  # Runs when _DEPLOY_TARGET is 'all' or 'ui'
  # ============================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-ui-agent'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$_DEPLOY_TARGET" = "all" ] || [ "$_DEPLOY_TARGET" = "ui" ]; then
          echo "Deploying UI agent..."
          gcloud builds submit --config=ui_test_execution_agent/deployment/cloud/cloudbuild.yaml \
            --substitutions=_SERVICE_NAME=$_UI_AGENT_SERVICE_NAME,_IMAGE_TAG=$_IMAGE_TAG \
            .
        else
          echo "Skipping UI agent deployment (_DEPLOY_TARGET=$_DEPLOY_TARGET)"
        fi
    dir: '/workspace'
    waitFor: [ 'maven-build' ]

  # ============================================
  # Stage 3: API Test Execution Agent (Cloud Run)
  # Delegates to the module's own cloudbuild.yaml
  # Runs when _DEPLOY_TARGET is 'all' or 'api'
  # ============================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-api-agent'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$_DEPLOY_TARGET" = "all" ] || [ "$_DEPLOY_TARGET" = "api" ]; then
          echo "Deploying API agent..."
          gcloud builds submit --config=api_test_execution_agent/deployment/cloud/cloudbuild.yaml \
            --substitutions=_SERVICE_NAME=$_API_AGENT_SERVICE_NAME,_IMAGE_TAG=$_IMAGE_TAG,_REGION=$_REGION,_PORT=8005,_MEMORY=$_API_AGENT_MEMORY,_CPU=$_API_AGENT_CPU,_EXTERNAL_URL=$_API_AGENT_EXTERNAL_URL \
            .
        else
          echo "Skipping API agent deployment (_DEPLOY_TARGET=$_DEPLOY_TARGET)"
        fi
    dir: '/workspace'
    waitFor: [ 'maven-build' ]

substitutions:
  _DEPLOY_TARGET: 'all'  # Options: 'all', 'ui', 'api'
  _UI_AGENT_SERVICE_NAME: 'ui-test-execution-agent'
  _API_AGENT_SERVICE_NAME: 'api-test-execution-agent'
  _IMAGE_TAG: 'latest'
  _REGION: 'us-central1'
  _API_AGENT_MEMORY: '2Gi'
  _API_AGENT_CPU: '1'
  _API_AGENT_EXTERNAL_URL: ''

options:
  logging: CLOUD_LOGGING_ONLY